# Generated by Django 4.0 on 2022-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment', models.CharField(max_length=300)),
                ('RegularPrivate', models.CharField(max_length=500)),
                ('Application', models.BigIntegerField()),
                ('RollNo', models.BigIntegerField()),
                ('StudentName', models.CharField(max_length=500)),
                ('FatherName', models.CharField(max_length=500)),
                ('MotherName', models.CharField(max_length=500)),
                ('BirthDate', models.CharField(max_length=300)),
                ('Hindi', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('SocialScience', models.IntegerField()),
                ('Sanskrite', models.IntegerField()),
            ],
        ),
    ]
